-- Creación de la base de datos
CREATE DATABASE IF NOT EXISTS app_formacion;

-- Conexión a las base de datos.
use app_formacion;

-- Creación de tablas
-- TABLA T_USUARIO
CREATE TABLE IF NOT EXISTS T_USUARIO(
  email VARCHAR(50) NOT NULL PRIMARY KEY,
  nickname VARCHAR(15) NOT NULL UNIQUE,
  fecha_alta DATETIME NOT NULL
);

-- TABLA T_ROL
CREATE TABLE IF NOT EXISTS T_ROL(
  codigo_rol CHAR(5) NOT NULL PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL,
  descripcion VARCHAR(250)
);

-- TABLA T_PERMISO
CREATE TABLE IF NOT EXISTS T_PERMISO(
  identificador_permiso INT NOT NULL PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL,
  descripcion VARCHAR(250) NULL
);


-- TABLA T_USUARIO_ROL
CREATE TABLE IF NOT EXISTS T_USUARIO_ROL(
  email VARCHAR(50) NOT NULL,
  codigo_rol CHAR(5) NOT NULL,
  PRIMARY KEY (email, codigo_rol),
  CONSTRAINT FK_USUARIOROL_USUARIO
	FOREIGN KEY (email) REFERENCES T_USUARIO(email),
  CONSTRAINT FK_USUARIOROL_ROL
	FOREIGN KEY (codigo_rol) REFERENCES T_ROL(codigo_rol)
);

-- TABLA T_ROL_PERMISO
CREATE TABLE IF NOT EXISTS T_ROL_PERMISO(
  codigo_rol CHAR(5) NOT NULL,
  identificador_permiso INT NOT NULL,
  PRIMARY KEY (codigo_rol, identificador_permiso),
  CONSTRAINT FK_ROLPERMISO_ROL
	FOREIGN KEY (codigo_rol) REFERENCES T_ROL(codigo_rol),
  CONSTRAINT FK_ROLPERMISO_PERMISO
	FOREIGN KEY (identificador_permiso) REFERENCES T_PERMISO(identificador_permiso)
);


-- Sentencias para la actividad 

-- TABLA T_PERSONAL
CREATE TABLE IF NOT EXISTS T_PERSONAL(
  DNI CHAR(9) NOT NULL PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,
  Apellido1 VARCHAR(50) NOT NULL,
  Apellido2 VARCHAR(50) NULL
);

-- TABLA T_FORMACION
CREATE TABLE IF NOT EXISTS T_FORMACION(
  Identificador INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(250) NOT NULL,
  GradoUniversitorio BOOL NOT NULL DEFAULT 1
);

-- TABLA T_GESTOR
CREATE TABLE IF NOT EXISTS T_GESTOR(
  DNI CHAR(9) NOT NULL PRIMARY KEY,
  CONSTRAINT FK_GESTOR_PERSONAL
    FOREIGN KEY (DNI) REFERENCES T_PERSONAL(DNI)
);

-- TABLA T_ALUMNO
CREATE TABLE IF NOT EXISTS T_ALUMNO(
  NumeroIdAlumno INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  FechaNacimiento DATE NOT NULL,
  DNI CHAR(9) NOT NULL UNIQUE,
  CONSTRAINT FK_ALUMNO_PERSONAL
    FOREIGN KEY (DNI) REFERENCES T_PERSONAL(DNI)
);

-- TABLA T_PROFESOR
CREATE TABLE IF NOT EXISTS T_PROFESOR(
  CodigoProfesor INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  DNI CHAR(9) NOT NULL UNIQUE,
  CONSTRAINT FK_PROFESOR_PERSONAL
    FOREIGN KEY (DNI) REFERENCES T_PERSONAL(DNI)
) AUTO_INCREMENT 1000;


-- TABLA T_FORMACION_PROFESOR
CREATE TABLE IF NOT EXISTS T_FORMACION_PROFESOR(
  CodigoProfesor INT NOT NULL,
  IdFormacion INT NOT NULL,
  PRIMARY KEY (CodigoProfesor, IdFormacion),
  CONSTRAINT FK_FORMACIONPROFESOR_PROFESOR
    FOREIGN KEY (CodigoProfesor) REFERENCES T_PROFESOR(CodigoProfesor),
  CONSTRAINT FK_FORMACIONPROFESOR_FORMACION
    FOREIGN KEY (IdFormacion) REFERENCES T_FORMACION(Identificador)
);

-- TABLA T_PERSONAL_USUARIO
CREATE TABLE IF NOT EXISTS T_PERSONAL_USUARIO(
  Email VARCHAR(50) NOT NULL,
  DNI CHAR(9) NOT NULL UNIQUE,
  PRIMARY KEY (Email, DNI),
  CONSTRAINT FK_PERSONALUSUARIO_PERSONAL
    FOREIGN KEY (DNI) REFERENCES T_PERSONAL(DNI),
  CONSTRAINT FK_PERSONALUSUARIO_USUARIO
    FOREIGN KEY (Email) REFERENCES T_USUARIO(email)
);

-- Cambios en TABLAS
-- Añadir Fecha y Hora de Baja de alumno
ALTER TABLE T_USUARIO ADD COLUMN FechaBaja DATETIME NULL;

-- Modificar el Identicadore asociados a T_PERMISO como INT AUTO_INCREMENT
-- 1º Borrar FK en T_ROL_PERMISO (PERMISO)
ALTER TABLE T_ROL_PERMISO DROP CONSTRAINT FK_ROLPERMISO_PERMISO;
ALTER TABLE T_ROL_PERMISO DROP CONSTRAINT FK_ROLPERMISO_ROL;
-- 2º Cambiar tipo IdPermiso en PK T_PERMISO
ALTER TABLE T_PERMISO MODIFY COLUMN identificador_permiso INT AUTO_INCREMENT NOT NULL;
-- 3º Borrar PK en T_ROL_PERMISO (PERMISO)
ALTER TABLE T_ROL_PERMISO DROP PRIMARY KEY;
-- 4º Cambiar el tipo de IdPermiso en T_ROL_PERMISO
ALTER TABLE T_PERMISO MODIFY COLUMN identificador_permiso INT AUTO_INCREMENT NOT NULL;
-- 5º Añadir PK en T_ROL_PERMISO (PERMISO)
ALTER TABLE T_ROL_PERMISO ADD PRIMARY KEY (codigo_rol,identificador_permiso);
-- 6º Añadir FK en T_ROL_PERMISO (PERMISO)
ALTER TABLE T_ROL_PERMISO ADD CONSTRAINT FK_ROLPERMISO_PERMISO FOREIGN KEY (identificador_permiso) REFERENCES T_PERMISO(identificador_permiso);
ALTER TABLE T_ROL_PERMISO ADD CONSTRAINT FK_ROLPERMISO_ROL FOREIGN KEY (codigo_rol) REFERENCES T_ROL(codigo_rol);
